### ISSUE TITLE
武林外传台词纠错，都似筛糠？

### ISSUE THREAD

**Issue by gMan1990** [LeoHaoVIP/leohaovip.github.io#1]
`白展堂面如土色，都似筛糠，只恨爹娘少生了两条腿。`

**Comment by LeoHaoVIP** [comment]
已更新！台词从第三方平台下载，已修改为 “抖似筛糠”。

**Comment by gMan1990** [comment]
1. 武林外传没了?
2. 主页的摩斯编码 `R.I.P.`

**Comment by LeoHaoVIP** [comment]
武林外传暂时从主页隐藏，但入口还在，路径为 /2022/11/06/swordsman-search
❤️

**Comment by gMan1990** [comment]
无了？
